# Generated by Django 5.2.6 on 2025-10-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hanzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=10)),
                ("traditional_word", models.CharField(max_length=10)),
                ("meaning", models.CharField(max_length=100)),
                ("sheet_level", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="User_Words",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("word", models.CharField(max_length=10)),
                ("meaning", models.CharField(max_length=100)),
                ("sheet_level", models.IntegerField(default=1)),
                ("last_studied", models.DateTimeField()),
                ("study_level", models.CharField(max_length=2)),
                ("word_level", models.IntegerField(default=1)),
                ("incorect_times", models.IntegerField(default=0)),
            ],
        ),
    ]
